export enum ApiStatusResponseEnum {
  Success = 'success',
  Error = 'error',
}

export enum MatchDefinedEnum {
  REGULAR = 'regular',
  EXTRA_TIME = 'extra',
  PENALTIES = 'penalties',
}

export const resultsKnockout = {
  '52': {
    _id: '638923be0eab2168b945af35',
    away_score: 1,
    away_extra_time_score: 1,
    away_penalties_score: 1,
    away_scorers: ['I. Perišić,Penalties(1)'],
    away_team_id: '20',
    finished: 'TRUE',
    group: 'R16',
    home_score: 1,
    home_extra_time_score: 1,
    home_penalties_score: 3,
    home_scorers: ['Daizen Maeda,Penalties(3)'],
    home_team_id: '18',
    id: '52',
    matchDefined: MatchDefinedEnum.PENALTIES,
    local_date: '12/5/2022 18:00',
    matchday: '16',
    persian_date: '1400-09-14 18:30',
    stadium_id: '1',
    time_elapsed: 'finished',
    type: 'R16',
    home_team_fa: 'کرواسی',
    away_team_fa: 'ژاپن',
    home_team_en: 'Croatia',
    away_team_en: 'Japan',
    home_flag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/125px-Flag_of_Croatia.svg.png',
    away_flag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/125px-Flag_of_Japan.svg.png',
  },
  '54': {
    _id: '638923be0eab2168b945af37',
    away_score: 0,
    away_extra_time_score: 0,
    away_penalties_score: 3,
    away_scorers: ['null'],
    away_team_id: '17',
    finished: 'FALSE',
    group: 'R16',
    home_score: 0,
    home_extra_time_score: 0,
    home_penalties_score: 0,
    home_scorers: ['null'],
    home_team_id: '21',
    id: '54',
    matchDefined: MatchDefinedEnum.PENALTIES,
    local_date: '12/6/2022 18:00',
    matchday: '17',
    persian_date: '1400-09-15 18:30',
    stadium_id: '1',
    time_elapsed: 'notstarted',
    type: 'R16',
    home_team_fa: 'اسپانیا',
    away_team_fa: 'مراکش',
    home_team_en: 'Spain',
    away_team_en: 'Morocco',
    home_flag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/125px-Flag_of_Spain.svg.png',
    away_flag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/125px-Flag_of_Morocco.svg.png',
  },
  '56': {
    _id: '6389265e0eab2168b945af3a',
    away_score: 0,
    away_extra_time_score: 1,
    away_penalties_score: 4,
    away_scorers: ['Bruno Petković,Penalties(4)'],
    away_team_id: '18',
    finished: 'TRUE',
    group: 'QR',
    home_score: 0,
    home_extra_time_score: 1,
    home_penalties_score: 2,
    home_scorers: ['Neymar,Penalties(2)'],
    home_team_id: '25',
    id: '56',
    matchDefined: MatchDefinedEnum.PENALTIES,
    local_date: '12/9/2022 18:00',
    matchday: '18',
    persian_date: '1400-09-18 18:30',
    stadium_id: '1',
    time_elapsed: 'finished',
    type: 'QR',
    home_team_fa: 'برزیل',
    away_team_fa: 'کرواسی',
    home_team_en: 'Brazil',
    away_team_en: 'Croatia',
    home_flag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/125px-Flag_of_Brazil.svg.png',
    away_flag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/125px-Flag_of_Croatia.svg.png',
  },
  '57': {
    _id: '6389265e0eab2168b945af3b',
    away_score: 2,
    away_scorers: ['N. Molina,L. Messi,Penalties(4)'],
    away_extra_time_score: 2,
    away_penalties_score: 4,
    away_team_id: '9',
    finished: 'TRUE',
    group: 'QR',
    home_score: 2,
    home_extra_time_score: 2,
    home_penalties_score: 3,
    home_scorers: ['W. Weghorst(2),Penalties(3)'],
    home_team_id: '4',
    id: '57',
    matchDefined: MatchDefinedEnum.PENALTIES,
    local_date: '12/9/2022 22:00',
    matchday: '18',
    persian_date: '1400-09-18 22:30',
    stadium_id: '1',
    time_elapsed: 'finished',
    type: 'QR',
    home_team_fa: 'هلند',
    away_team_fa: 'آرژانتین',
    home_team_en: 'Netherlands',
    away_team_en: 'Argentina',
    home_flag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/125px-Flag_of_the_Netherlands.svg.png',
    away_flag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/125px-Flag_of_Argentina.svg.png',
  },
  '61': {
    _id: '6389265e0eab2168b945af3f',
    away_score: 0,
    away_scorers: ['null'],
    away_team_id: '17',
    finished: 'TRUE',
    group: 'semi',
    home_score: 2,
    home_scorers: ['Theo Hernández,Randal Kolo Muani'],
    home_team_id: '15',
    id: '61',
    local_date: '12/14/2022 22:00',
    matchday: '21',
    persian_date: '1400-09-23 22:30',
    stadium_id: '1',
    time_elapsed: 'finished',
    type: 'semi',
    home_team_fa: 'فرانسه',
    away_team_fa: 'مراکش',
    home_team_en: 'France',
    away_team_en: 'Morocco',
    home_flag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%2C_2020%E2%80%93present%29.svg/125px-Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%2C_2020%E2%80%93present%29.svg.png',
    away_flag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/125px-Flag_of_Morocco.svg.png',
  },
};
